name: okoto
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Utils
  flutter_native_splash: ^2.2.16
  shared_preferences: ^2.0.17

  #State Management
  provider: ^6.0.5

  #Firebase
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.3.1
  firebase_analytics: ^10.1.0
  firebase_crashlytics: ^3.0.11
  firebase_messaging: ^14.2.1

  #UI
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/