name: okoto
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Utils
  connectivity_plus: ^3.0.2
  flutter_native_splash: ^2.2.16
  intl: ^0.17.0
  shared_preferences: ^2.0.17
  url_launcher: ^6.1.8
  uuid: ^3.0.7

  #State Management
  provider: ^6.0.5

  #Firebase
  cloud_firestore: ^4.3.1
  firebase_analytics: ^10.1.0
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  firebase_crashlytics: ^3.0.11
  firebase_messaging: ^14.2.1

  #UI
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.1.2
  google_fonts: ^4.0.1
  loading_animation_widget: ^1.2.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/