name: okoto
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Utils
  add_2_calendar: ^2.2.3
  connectivity_plus: ^3.0.2
  flutter_native_splash: ^2.2.16
  http: ^0.13.5
  intl: ^0.17.0
  shared_preferences: ^2.0.17
  url_launcher: ^6.1.8
  uuid: ^3.0.7
  webview_flutter: ^4.0.2

  #State Management
  provider: ^6.0.5

  #Firebase
  cloud_firestore: ^4.3.1
  firebase_analytics: ^10.1.0
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  firebase_crashlytics: ^3.0.11
  firebase_messaging: ^14.2.1

  #Payment
  razorpay_flutter: ^1.3.4

  #UI
  cached_network_image: ^3.2.3
  circular_countdown_timer: ^0.2.3
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.1.2
  flutter_spinkit: ^5.1.0
  google_fonts: ^4.0.1
  loading_animation_widget: ^1.2.0+4
  material_design_icons_flutter: ^6.0.7096
#  overlay_support: ^2.1.0
  shimmer: ^2.0.0
  timer_count_down: ^2.2.2
#  top_snackbar_flutter: ^3.0.0+1
  my_popup_snakbar:
    git:
      url: https://github.com/Rockstar95/my_popup_snakbar
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/